############################################
# GitHub Actions pipeline template 
############################################

name: GitHub Actions Pipeline Template

# TODO: parameters/inputs

on:
  # Manual pipeline enablement
  workflow_dispatch:
  # Automated pipeline triggers
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  template1_dev:
    uses: ./.github/workflows/template1.yml
    with:
      environment: 'dev'
      input1: 'DEV Input 1'
      input2: 'DEV Input 2'
      # Override GitHub Actions rnuner
      # runs-on: 'ubuntu-18.04'
  template1_prod:
    uses: ./.github/workflows/template1.yml
    with:
      environment: 'prod'
      input1: 'PROD Input 1'
      input2: 'PROD Input 2'
      # Override GitHub Actions rnuner
      # runs-on: 'ubuntu-18.04'
  template2_dev:
    uses: ./.github/workflows/template2.yml
    with:
      environment: 'dev'
      input1: 'DEV Input 1'
      input2: 'DEV Input 2'
      testneeds: 'template1_dev'
      # Override GitHub Actions rnuner
      # runs-on: 'ubuntu-18.04'
  template2_prod:
    uses: ./.github/workflows/template2.yml
    with:
      environment: 'prod'
      input1: 'PROD Input 1'
      input2: 'PROD Input 2'
      testneeds: 'template1_prod'
      # Override GitHub Actions rnuner
      # runs-on: 'ubuntu-18.04'

# TODO: depends on