############################################
# GitHub Actions pipeline template 
############################################

name: GitHub Actions Pipeline Template

# TODO: parameters/inputs

on:
  # Manual pipeline enablement
  workflow_dispatch:
  # Automated pipeline triggers
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  template1:
    uses: ./.github/workflows/template1.yml
    with:
      environment: 'dev'
      input1: 'Markham'
      input2: 'Ontario'
  template2:
    uses: ./.github/workflows/template2.yml
    with:
      input1: 'Toronto'
      input2: 'Ontario'
