############################################
# GitHub Actions pipeline template 
############################################

name: GitHub Actions Pipeline Template

# TODO: parameters/inputs

on:
  # Manual pipeline enablement
  workflow_dispatch:
  # Automated pipeline triggers
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  gha-pipeline-template:
    runs-on: 'ubuntu-20.04'
  template1:
    # TODO: Remove branch reference
    uses: ./.github/workflows/template1.yml
