############################################
# GitHub Actions pipeline template 1
############################################

name: GitHub Actions Pipeline Template 1

on:
  workflow_call:
    # inputs:
    #   username:
    #     required: true
    #     type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  template1:
    name: Template 1
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Hello world
        run: |
          echo "Hello world"
