############################################
# GitHub Actions workflow template 2
############################################

name: GitHub Actions Workflow Template 2

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      input1:
        required: true
        type: string
      input2:
        required: true
        type: string
      runs-on:
        default: 'ubuntu-20.04'
        required: false
        type: string

jobs:
  template2:
    name: Template 2
    environment: '${{ inputs.environment }}'
    runs-on: '${{ inputs.runs-on }}'
    steps:
      - name: Goodbye world
        run: |
          echo "Goodbye world"
      - name: Display inputs
        run: |
          echo "Input 1: ${{ inputs.input1 }}"
          echo "Input 2: ${{ inputs.input2 }}"
          echo "Needs: ${{ inputs.needs }}"
      - name: Display variables
        run: |
          echo "MY_VAR_1: ${MY_VAR_1}"
          echo "MY_VAR_2: ${{ env.MY_VAR_2 }}"